### PR TITLE
To check what has been done so far

### PR DESCRIPTION
**Pull request by Oluwa-nifemi**

### CODE REVIEW

**Comment by ashinzekene** [comment]
Your JS is well written, well structured. :+1: 

Your designs however are below par and your site is not mobile responsive

GOod job though

**Comment by Oluwa-nifemi** [comment]
Yeah I'm not very strong at UI and had not had time to implement responsiveness. I've done that now

**Comment by Oluwa-nifemi** [comment]
To submit project

**Comment by Oluwa-nifemi** [comment]
Done

**Pull request merged**
